steps:
  # 종속성 설치
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'BE'
  
  # 빌드 실행
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'BE'
  
  # Google App Engine 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', './BE/app.yaml']
    dir: 'BE'
